version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src/PhotoBoothService"
    schedule:
      interval: "weekly"
    groups:
      Redhat .NET base images:
        patterns:
          - "*dotnet*"
    
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"