
// This file has been generated by the GUI designer. Do not modify.
namespace com.prodg.photobooth.presentation.widget
{
	public partial class OverlayedImageWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget com.prodg.photobooth.OverlayedImageWidget
			this.Hide ();
		}
	}
}
