
// This file has been generated by the GUI designer. Do not modify.

using Gtk;

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Image imagePhoto;
	
	private global::Gtk.Image imageInstruction;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.WindowPosition = WindowPosition.CenterAlways;
		this.OverrideBackgroundColor(StateFlags.Normal, new Gdk.RGBA { Red = 1.0, Green = 0.792, Blue = 0.765, Alpha = 1.0 }); // Sets background to #ffcac3
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.OverrideBackgroundColor(StateFlags.Normal, new Gdk.RGBA { Red = 1.0, Green = 0.792, Blue = 0.765, Alpha = 1.0 }); // Sets background to #ffcac3
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 0;
		this.vbox1.Margin = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.imageInstruction = new global::Gtk.Image ();
		this.imageInstruction.WidthRequest = 1280;
		this.imageInstruction.HeightRequest = 200;
		this.imageInstruction.Name = "imageInstruction";
		this.vbox1.Add (this.imageInstruction);
		global::Gtk.Box.BoxChild w0 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.imageInstruction]));
		w0.PackType = PackType.Start;
		w0.Position = 0;
		w0.Expand = false;
		w0.Fill = false;
		w0.Padding = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.imagePhoto = new global::Gtk.Image ();
		this.imagePhoto.HeightRequest = 800;
		this.imagePhoto.Name = "imagePhoto";
		this.imagePhoto.OverrideBackgroundColor(StateFlags.Normal, new Gdk.RGBA { Red = 1.0, Green = 0.792, Blue = 0.765, Alpha = 1.0 }); // Sets background to #ffcac3
		this.vbox1.Add (this.imagePhoto);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.imagePhoto]));
		w1.PackType = PackType.Start;
		w1.Position = 1;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 0;
		this.statusbar1.Margin = 0;
		this.statusbar1.WidthRequest = 1280;
		this.statusbar1.HeightRequest = 20;
		this.statusbar1.MessageArea.HeightRequest = 20;
		this.statusbar1.MessageArea.WidthRequest = 1280;
		this.statusbar1.MessageArea.Expand = false;
		this.statusbar1.MessageArea.Valign = Align.Center;
		this.statusbar1.MessageArea.Halign = Align.Center;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w3.PackType = PackType.Start;
		w3.Position = 2;
		w3.Expand = false;
		w3.Padding = 0;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1280;
		this.DefaultHeight = 1024;
		this.Margin = 0;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
