/* 
 * ItsMyParty.Photobooth.API
 *
 * ItsMyParty.Photobooth.API (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using ItsMyParty.Photobooth.Client;
using RestSharp;

namespace ItsMyParty.Photobooth.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISessionApiApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a session for an event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>SessionDTO</returns>
        SessionDTO CreateEventSession (long? eventId, SessionDTO session = null);

        /// <summary>
        /// Create a session for an event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        ApiResponse<SessionDTO> CreateEventSessionWithHttpInfo (long? eventId, SessionDTO session = null);
        /// <summary>
        /// Delete session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns></returns>
        void DeleteSession (long? sessionId);

        /// <summary>
        /// Delete session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteSessionWithHttpInfo (long? sessionId);
        /// <summary>
        /// Find session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>SessionDTO</returns>
        SessionDTO GetSessionById (long? sessionId);

        /// <summary>
        /// Find session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        ApiResponse<SessionDTO> GetSessionByIdWithHttpInfo (long? sessionId);
        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>SessionDTO</returns>
        SessionDTO GetSessionByIndex (long? eventId, int? sessionIndex);

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        ApiResponse<SessionDTO> GetSessionByIndexWithHttpInfo (long? eventId, int? sessionIndex);
        /// <summary>
        /// Find sessions by Event ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>SessionDTO</returns>
        SessionDTO GetSessionsByEventId (long? eventId, int? skip = null, int? limit = null);

        /// <summary>
        /// Find sessions by Event ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        ApiResponse<SessionDTO> GetSessionsByEventIdWithHttpInfo (long? eventId, int? skip = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create a session for an event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>Task of SessionDTO</returns>
        System.Threading.Tasks.Task<SessionDTO> CreateEventSessionAsync (long? eventId, SessionDTO session = null);

        /// <summary>
        /// Create a session for an event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<SessionDTO>> CreateEventSessionAsyncWithHttpInfo (long? eventId, SessionDTO session = null);
        /// <summary>
        /// Delete session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteSessionAsync (long? sessionId);

        /// <summary>
        /// Delete session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSessionAsyncWithHttpInfo (long? sessionId);
        /// <summary>
        /// Find session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>Task of SessionDTO</returns>
        System.Threading.Tasks.Task<SessionDTO> GetSessionByIdAsync (long? sessionId);

        /// <summary>
        /// Find session by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionByIdAsyncWithHttpInfo (long? sessionId);
        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>Task of SessionDTO</returns>
        System.Threading.Tasks.Task<SessionDTO> GetSessionByIndexAsync (long? eventId, int? sessionIndex);

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionByIndexAsyncWithHttpInfo (long? eventId, int? sessionIndex);
        /// <summary>
        /// Find sessions by Event ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>Task of SessionDTO</returns>
        System.Threading.Tasks.Task<SessionDTO> GetSessionsByEventIdAsync (long? eventId, int? skip = null, int? limit = null);

        /// <summary>
        /// Find sessions by Event ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionsByEventIdAsyncWithHttpInfo (long? eventId, int? skip = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SessionApiApi : ISessionApiApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionApiApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SessionApiApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionApiApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SessionApiApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create a session for an event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>SessionDTO</returns>
        public SessionDTO CreateEventSession (long? eventId, SessionDTO session = null)
        {
             ApiResponse<SessionDTO> localVarResponse = CreateEventSessionWithHttpInfo(eventId, session);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a session for an event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        public ApiResponse< SessionDTO > CreateEventSessionWithHttpInfo (long? eventId, SessionDTO session = null)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->CreateEventSession");

            var localVarPath = "/api/v1/events/{eventId}/sessions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (session != null && session.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(session); // http body (model) parameter
            }
            else
            {
                localVarPostBody = session; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEventSession", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Create a session for an event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>Task of SessionDTO</returns>
        public async System.Threading.Tasks.Task<SessionDTO> CreateEventSessionAsync (long? eventId, SessionDTO session = null)
        {
             ApiResponse<SessionDTO> localVarResponse = await CreateEventSessionAsyncWithHttpInfo(eventId, session);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a session for an event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be created</param>
        /// <param name="session">session created for storing shots (optional)</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SessionDTO>> CreateEventSessionAsyncWithHttpInfo (long? eventId, SessionDTO session = null)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->CreateEventSession");

            var localVarPath = "/api/v1/events/{eventId}/sessions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (session != null && session.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(session); // http body (model) parameter
            }
            else
            {
                localVarPostBody = session; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEventSession", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Delete session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns></returns>
        public void DeleteSession (long? sessionId)
        {
             DeleteSessionWithHttpInfo(sessionId);
        }

        /// <summary>
        /// Delete session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteSessionWithHttpInfo (long? sessionId)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
                throw new ApiException(400, "Missing required parameter 'sessionId' when calling SessionApiApi->DeleteSession");

            var localVarPath = "/api/v1/sessions/{sessionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sessionId != null) localVarPathParams.Add("sessionId", Configuration.ApiClient.ParameterToString(sessionId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSession", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteSessionAsync (long? sessionId)
        {
             await DeleteSessionAsyncWithHttpInfo(sessionId);

        }

        /// <summary>
        /// Delete session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the event for which the session needs to be deleted</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSessionAsyncWithHttpInfo (long? sessionId)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
                throw new ApiException(400, "Missing required parameter 'sessionId' when calling SessionApiApi->DeleteSession");

            var localVarPath = "/api/v1/sessions/{sessionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sessionId != null) localVarPathParams.Add("sessionId", Configuration.ApiClient.ParameterToString(sessionId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSession", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Find session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>SessionDTO</returns>
        public SessionDTO GetSessionById (long? sessionId)
        {
             ApiResponse<SessionDTO> localVarResponse = GetSessionByIdWithHttpInfo(sessionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        public ApiResponse< SessionDTO > GetSessionByIdWithHttpInfo (long? sessionId)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
                throw new ApiException(400, "Missing required parameter 'sessionId' when calling SessionApiApi->GetSessionById");

            var localVarPath = "/api/v1/sessions/{sessionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sessionId != null) localVarPathParams.Add("sessionId", Configuration.ApiClient.ParameterToString(sessionId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Find session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>Task of SessionDTO</returns>
        public async System.Threading.Tasks.Task<SessionDTO> GetSessionByIdAsync (long? sessionId)
        {
             ApiResponse<SessionDTO> localVarResponse = await GetSessionByIdAsyncWithHttpInfo(sessionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find session by ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">ID of the session which needs to be fetched</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionByIdAsyncWithHttpInfo (long? sessionId)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
                throw new ApiException(400, "Missing required parameter 'sessionId' when calling SessionApiApi->GetSessionById");

            var localVarPath = "/api/v1/sessions/{sessionId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sessionId != null) localVarPathParams.Add("sessionId", Configuration.ApiClient.ParameterToString(sessionId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>SessionDTO</returns>
        public SessionDTO GetSessionByIndex (long? eventId, int? sessionIndex)
        {
             ApiResponse<SessionDTO> localVarResponse = GetSessionByIndexWithHttpInfo(eventId, sessionIndex);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        public ApiResponse< SessionDTO > GetSessionByIndexWithHttpInfo (long? eventId, int? sessionIndex)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->GetSessionByIndex");
            // verify the required parameter 'sessionIndex' is set
            if (sessionIndex == null)
                throw new ApiException(400, "Missing required parameter 'sessionIndex' when calling SessionApiApi->GetSessionByIndex");

            var localVarPath = "/api/v1/events/{eventId}/sessions/{sessionIndex}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (sessionIndex != null) localVarPathParams.Add("sessionIndex", Configuration.ApiClient.ParameterToString(sessionIndex)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionByIndex", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>Task of SessionDTO</returns>
        public async System.Threading.Tasks.Task<SessionDTO> GetSessionByIndexAsync (long? eventId, int? sessionIndex)
        {
             ApiResponse<SessionDTO> localVarResponse = await GetSessionByIndexAsyncWithHttpInfo(eventId, sessionIndex);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find sessions for a specific event by the index of the session in this event 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which the session needs to be fetched</param>
        /// <param name="sessionIndex">Index of the session in the event which needs to be fetched</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionByIndexAsyncWithHttpInfo (long? eventId, int? sessionIndex)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->GetSessionByIndex");
            // verify the required parameter 'sessionIndex' is set
            if (sessionIndex == null)
                throw new ApiException(400, "Missing required parameter 'sessionIndex' when calling SessionApiApi->GetSessionByIndex");

            var localVarPath = "/api/v1/events/{eventId}/sessions/{sessionIndex}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (sessionIndex != null) localVarPathParams.Add("sessionIndex", Configuration.ApiClient.ParameterToString(sessionIndex)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionByIndex", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Find sessions by Event ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>SessionDTO</returns>
        public SessionDTO GetSessionsByEventId (long? eventId, int? skip = null, int? limit = null)
        {
             ApiResponse<SessionDTO> localVarResponse = GetSessionsByEventIdWithHttpInfo(eventId, skip, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find sessions by Event ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of SessionDTO</returns>
        public ApiResponse< SessionDTO > GetSessionsByEventIdWithHttpInfo (long? eventId, int? skip = null, int? limit = null)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->GetSessionsByEventId");

            var localVarPath = "/api/v1/events/{eventId}/sessions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (skip != null) localVarQueryParams.Add("skip", Configuration.ApiClient.ParameterToString(skip)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionsByEventId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

        /// <summary>
        /// Find sessions by Event ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>Task of SessionDTO</returns>
        public async System.Threading.Tasks.Task<SessionDTO> GetSessionsByEventIdAsync (long? eventId, int? skip = null, int? limit = null)
        {
             ApiResponse<SessionDTO> localVarResponse = await GetSessionsByEventIdAsyncWithHttpInfo(eventId, skip, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find sessions by Event ID 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eventId">ID of the event for which sessions needs to be fetched</param>
        /// <param name="skip"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>Task of ApiResponse (SessionDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SessionDTO>> GetSessionsByEventIdAsyncWithHttpInfo (long? eventId, int? skip = null, int? limit = null)
        {
            // verify the required parameter 'eventId' is set
            if (eventId == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling SessionApiApi->GetSessionsByEventId");

            var localVarPath = "/api/v1/events/{eventId}/sessions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (eventId != null) localVarPathParams.Add("eventId", Configuration.ApiClient.ParameterToString(eventId)); // path parameter
            if (skip != null) localVarQueryParams.Add("skip", Configuration.ApiClient.ParameterToString(skip)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionsByEventId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SessionDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SessionDTO) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SessionDTO)));
        }

    }
}
