name: CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/CI.yml"
      - "src/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/CI.yml"
      - "src/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: Build and Test
    outputs:
      version: ${{ github.ref == 'refs/heads/main' && steps.version_release.outputs.version || steps.version_prerelease.outputs.version }}
      version_tag : ${{ steps.version_release.outputs.version_tag }}
    permissions:
      contents: read
      statuses: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Git Semantic Version Pre-Release
        uses: PaulHatch/semantic-version@v5.3.0
        id: version_prerelease
        with:
          version_format: "${major}.${minor}.${patch}-pre${increment}"
          change_path: "src"

      - name: Git Semantic Version Release
        uses: PaulHatch/semantic-version@v5.3.0
        id: version_release
        with:
          version_format: "${major}.${minor}.${patch}"
          change_path: "src"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          sbom: true
          cache-from: bronneberg/photobooth-service:cache
          cache-to: bronneberg/photobooth-service:cache
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bronneberg/photobooth-service:latest, bronneberg/photobooth-service:${{ github.ref == 'refs/heads/main' && steps.version_release.outputs.version || steps.version_prerelease.outputs.version }}

  vulnerability-test:
    name: Vulnerability Test
    needs: build
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      statuses: write
      checks: write

    steps:
      - name: Pull Docker image from cache
        env:
          IMAGE_TAG: ${{ needs.build.outputs.version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_APIKEY: ${{ secrets.DOCKER_APIKEY }}
        run: |
          docker login --username ${DOCKER_USERNAME} --password ${DOCKER_APIKEY}
          docker pull bronneberg/photobooth-service:$IMAGE_TAG

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bronneberg/photobooth-service:${{ needs.build.outputs.version }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
  
  create-release:
    name: Create Release
    needs: [ build, vulnerability-test]
    runs-on: [ ubuntu-latest ]
    if: ${{ github.actor != 'dependabot[bot]' }} AND ${{github.ref == 'refs/heads/main'}}
    permissions:
      id-token: write
      contents: write
        
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ needs.build.outputs.version_tag  }}
          name: "Version ${{ needs.build.outputs.version }}"
          prerelease: false
          target_commitish: ${{ github.ref }}